"use client";

import { useState, type ReactNode } from "react";
import { Button } from "@hireops/ui";
import { Badge } from "@/components/ui";
import type { BadgeTone } from "@/components/ui";
import { trpc } from "@/lib/trpc-client";
import type {
  AiInterviewCoverage,
  AiInterviewEvidence,
  AiInterviewEvidenceAnswer,
  AiInterviewKnockoutStatus,
  AiInterviewQuestionEvidence,
  AiInterviewRelevance,
} from "@hireops/api-types";

/**
 * AI-INT-3 — the recruiter's EVIDENCE REPORT for a submitted AI round, shown
 * inside AiInterviewRoundSection.
 *
 * EVIDENCE, NOT A VERDICT. Every label here describes the candidate's WORDS
 * against the question and the round's rubric — does the answer address the
 * question, does it speak to this criterion, did they state the requirement —
 * and every quote is verbatim (the drain drops any that is not). There is no
 * score, rank or recommendation, and the copy stays factual on purpose: the
 * decision is made by the panel in the scorecard flow, which the AI never
 * fills.
 *
 * Compact by default: a summary strip, then one collapsed row per question
 * that expands to the answer, the relevance note and the rubric evidence.
 *
 * No playback: the recording has no signed read URL today, so a spoken
 * answer shows where it starts in the recording (mm:ss) instead of a player.
 */

const DECISION_LINE =
  "Evidence to support the panel's judgement — the decision stays with the panel.";

const RELEVANCE_LABEL: Record<AiInterviewRelevance, string> = {
  addresses: "Addresses the question",
  partially_addresses: "Partially addresses",
  off_topic: "Off topic",
  no_answer: "No answer",
};
const RELEVANCE_TONE: Record<AiInterviewRelevance, BadgeTone> = {
  addresses: "success",
  partially_addresses: "warning",
  off_topic: "neutral",
  no_answer: "neutral",
};

const COVERAGE_LABEL: Record<AiInterviewCoverage, string> = {
  covered: "Covered",
  partial: "Partial",
  not_covered: "Not covered",
};
const COVERAGE_TONE: Record<AiInterviewCoverage, BadgeTone> = {
  covered: "success",
  partial: "warning",
  not_covered: "neutral",
};

const KNOCKOUT_LABEL: Record<AiInterviewKnockoutStatus, string> = {
  confirmed: "Confirmed",
  contradicted: "Contradicted",
  not_mentioned: "Not mentioned",
};
const KNOCKOUT_TONE: Record<AiInterviewKnockoutStatus, BadgeTone> = {
  confirmed: "success",
  contradicted: "error",
  not_mentioned: "neutral",
};

const POLL_MS = 10_000;

function fmtWhen(iso: string | null): string {
  if (!iso) return "—";
  const d = new Date(iso);
  if (Number.isNaN(d.getTime())) return "—";
  return d.toLocaleString("en-IN", {
    day: "numeric",
    month: "short",
    hour: "2-digit",
    minute: "2-digit",
  });
}

/** Offset into the round recording → mm:ss (h:mm:ss past an hour). */
function fmtOffset(ms: number): string {
  const total = Math.max(0, Math.floor(ms / 1000));
  const h = Math.floor(total / 3600);
  const m = Math.floor((total % 3600) / 60);
  const s = total % 60;
  const mmss = `${String(m).padStart(2, "0")}:${String(s).padStart(2, "0")}`;
  return h > 0 ? `${h}:${mmss}` : mmss;
}

function questionOrder(key: string): number {
  const n = parseInt(key.replace(/^q/, ""), 10);
  return Number.isNaN(n) ? Number.MAX_SAFE_INTEGER : n;
}

export function AiInterviewEvidencePanel({
  interviewId,
  rubricLabels,
  integrity,
}: {
  interviewId: string;
  /** rubric key → label, from the session card. */
  rubricLabels: ReadonlyMap<string, string>;
  /** The card's existing IntegrityLine, rendered in the summary strip. */
  integrity: ReactNode;
}) {
  const utils = trpc.useUtils();
  const q = trpc.getAiInterviewEvidence.useQuery(
    { interviewId },
    {
      // Auto-refresh only while the drain is working on it.
      refetchInterval: (query) => {
        const status = query.state.data?.status;
        return status === "pending" || status === "processing" ? POLL_MS : false;
      },
    },
  );
  const regenerate = trpc.regenerateAiInterviewEvidence.useMutation({
    onSuccess: () => void utils.getAiInterviewEvidence.invalidate({ interviewId }),
  });

  const header = (
    <div className="mb-2">
      <div className="flex flex-wrap items-center gap-2">
        <span className="font-semibold text-neutral-700">Evidence report</span>
        {q.data?.status === "done" && (q.data.model || q.data.promptVersion) ? (
          <span className="text-[11px] text-neutral-400">
            Generated by {q.data.model ?? "unknown model"}
            {q.data.promptVersion ? ` · prompt ${q.data.promptVersion}` : ""} ·{" "}
            {fmtWhen(q.data.generatedAt)}
          </span>
        ) : null}
      </div>
      <p className="mt-1 text-neutral-600">{DECISION_LINE}</p>
    </div>
  );

  function body() {
    if (q.isLoading) return <p className="text-neutral-500">Loading evidence report…</p>;
    if (q.error) return <p className="text-status-error-700">{q.error.message}</p>;
    if (!q.data) return null;
    const { status, evidence, answers, lastError } = q.data;
    const busy = regenerate.isPending;

    if (status === "pending" || status === "processing") {
      return (
        <>
          {integrity}
          <p className="mt-2 text-neutral-500">
            Preparing the evidence report… (it follows the transcript)
          </p>
        </>
      );
    }
    if (status === "none") {
      return (
        <>
          {integrity}
          <p className="mt-2 text-neutral-500">No evidence report has been generated yet.</p>
          <Button
            className="mt-2"
            variant="primary"
            size="sm"
            disabled={busy}
            onClick={() => regenerate.mutate({ interviewId })}
          >
            {busy ? "Queuing…" : "Generate evidence report"}
          </Button>
        </>
      );
    }
    if (status === "failed") {
      return (
        <>
          {integrity}
          <p className="mt-2 text-status-error-700">
            {lastError ?? "The evidence report could not be generated."}
          </p>
          <Button
            className="mt-2"
            variant="secondary"
            size="sm"
            disabled={busy}
            onClick={() => regenerate.mutate({ interviewId })}
          >
            {busy ? "Queuing…" : "Try again"}
          </Button>
        </>
      );
    }
    if (status === "skipped") {
      return (
        <>
          {integrity}
          <p className="mt-2 text-neutral-500">
            No evidence report was generated.{" "}
            {lastError ??
              "Either evidence reports are switched off for this tenant, or there were no usable answers."}
          </p>
          <Button
            className="mt-2"
            variant="secondary"
            size="sm"
            disabled={busy}
            onClick={() => regenerate.mutate({ interviewId })}
          >
            {busy ? "Queuing…" : "Generate again"}
          </Button>
        </>
      );
    }
    // done
    if (!evidence) {
      return (
        <>
          {integrity}
          <p className="mt-2 text-neutral-500">The stored evidence report could not be read.</p>
        </>
      );
    }
    return (
      <EvidenceReport
        evidence={evidence}
        answers={answers}
        rubricLabels={rubricLabels}
        integrity={integrity}
      />
    );
  }

  return (
    <div className="mt-3 rounded-md border border-neutral-200 bg-white p-3">
      {header}
      {body()}
      {regenerate.error ? (
        <p className="mt-2 text-status-error-700">{regenerate.error.message}</p>
      ) : null}
    </div>
  );
}

function EvidenceReport({
  evidence,
  answers,
  rubricLabels,
  integrity,
}: {
  evidence: AiInterviewEvidence;
  answers: AiInterviewEvidenceAnswer[];
  rubricLabels: ReadonlyMap<string, string>;
  integrity: ReactNode;
}) {
  const [open, setOpen] = useState<ReadonlySet<string>>(new Set());
  const answerByKey = new Map(answers.map((a) => [a.questionKey, a]));
  const questions = [...evidence.questions].sort(
    (a, b) => questionOrder(a.questionKey) - questionOrder(b.questionKey),
  );

  const unavailable = (qe: AiInterviewQuestionEvidence) =>
    qe.transcriptUnavailable || answerByKey.get(qe.questionKey)?.transcriptUnavailable === true;

  const addressed = questions.filter((qe) => qe.relevance === "addresses").length;
  const partially = questions.filter((qe) => qe.relevance === "partially_addresses").length;
  const unavailableCount = questions.filter(unavailable).length;

  // Rubric tallies across questions. A lost transcript is not counted as
  // "not covered" — that would turn a pipeline gap into a fact about the person.
  const tallies = new Map<string, Record<AiInterviewCoverage, number>>();
  for (const qe of questions) {
    if (unavailable(qe)) continue;
    for (const r of qe.rubric) {
      const t = tallies.get(r.rubricKey) ?? { covered: 0, partial: 0, not_covered: 0 };
      t[r.coverage] += 1;
      tallies.set(r.rubricKey, t);
    }
  }

  function toggle(key: string) {
    setOpen((prev) => {
      const next = new Set(prev);
      if (next.has(key)) next.delete(key);
      else next.add(key);
      return next;
    });
  }

  return (
    <div>
      {/* ── summary strip ── */}
      <div className="rounded-md border border-neutral-200 bg-neutral-50/60 p-2">
        <p className="text-neutral-700">
          {evidence.meta.answeredCount} of {evidence.meta.questionCount} answered · {addressed}{" "}
          fully address the question · {partially} partially
          {unavailableCount > 0 ? ` · ${unavailableCount} transcript unavailable` : ""}
        </p>
        {tallies.size > 0 ? (
          <div className="mt-1 flex flex-wrap items-center gap-1">
            <span className="text-neutral-500">Rubric:</span>
            {[...tallies.entries()].map(([key, t]) => (
              <RubricTallyChip key={key} label={rubricLabels.get(key) ?? key} tally={t} />
            ))}
          </div>
        ) : null}
        {integrity}
        {evidence.summary ? <p className="mt-2 text-neutral-700">{evidence.summary}</p> : null}
      </div>

      {/* ── per question ── */}
      <ol className="mt-2 space-y-1">
        {questions.map((qe) => (
          <QuestionEvidenceRow
            key={qe.questionKey}
            qe={qe}
            answer={answerByKey.get(qe.questionKey) ?? null}
            unavailable={unavailable(qe)}
            rubricLabels={rubricLabels}
            expanded={open.has(qe.questionKey)}
            onToggle={() => toggle(qe.questionKey)}
          />
        ))}
      </ol>

      {/* ── knockouts ── */}
      {evidence.knockouts.length > 0 ? (
        <div className="mt-3">
          <p className="mb-1 text-[11px] font-medium uppercase tracking-wide text-neutral-500">
            Requirements
          </p>
          <ul className="space-y-1">
            {evidence.knockouts.map((k, i) => (
              <li key={`${i}-${k.question}`} className="rounded-md border border-neutral-200 p-2">
                <div className="flex flex-wrap items-start gap-2">
                  <Badge tone={KNOCKOUT_TONE[k.status]}>{KNOCKOUT_LABEL[k.status]}</Badge>
                  <span className="min-w-0 flex-1 text-neutral-800">{k.question}</span>
                </div>
                {k.quote ? (
                  <Quote>
                    {k.quote}
                    {k.questionKey ? (
                      <span className="ml-1 not-italic text-neutral-400">
                        ({k.questionKey.toUpperCase()})
                      </span>
                    ) : null}
                  </Quote>
                ) : null}
              </li>
            ))}
          </ul>
        </div>
      ) : null}

      {evidence.meta.quotesDropped > 0 ? (
        <p className="mt-2 text-[11px] text-neutral-400">
          {evidence.meta.quotesDropped} quote{evidence.meta.quotesDropped === 1 ? "" : "s"} the
          model produced {evidence.meta.quotesDropped === 1 ? "was" : "were"} not found
          word-for-word in the answers and {evidence.meta.quotesDropped === 1 ? "was" : "were"}{" "}
          removed.
        </p>
      ) : null}
    </div>
  );
}

function RubricTallyChip({
  label,
  tally,
}: {
  label: string;
  tally: Record<AiInterviewCoverage, number>;
}) {
  const parts: string[] = [];
  if (tally.covered > 0) parts.push(`${tally.covered} covered`);
  if (tally.partial > 0) parts.push(`${tally.partial} partial`);
  if (tally.not_covered > 0) parts.push(`${tally.not_covered} not covered`);
  return (
    <span className="inline-flex items-center rounded-full bg-neutral-100 px-2 py-0.5 text-[11px] font-medium text-neutral-600">
      {label}: {parts.join(" · ")}
    </span>
  );
}

function QuestionEvidenceRow({
  qe,
  answer,
  unavailable,
  rubricLabels,
  expanded,
  onToggle,
}: {
  qe: AiInterviewQuestionEvidence;
  answer: AiInterviewEvidenceAnswer | null;
  unavailable: boolean;
  rubricLabels: ReadonlyMap<string, string>;
  expanded: boolean;
  onToggle: () => void;
}) {
  const mode = qe.answerMode ?? answer?.mode ?? null;
  const startMs = qe.answerStartMs ?? answer?.answerStartMs ?? null;

  return (
    <li className="rounded-md border border-neutral-200">
      <button
        type="button"
        onClick={onToggle}
        aria-expanded={expanded}
        className="flex w-full flex-wrap items-center gap-2 p-2 text-left hover:bg-neutral-50"
      >
        <span className="shrink-0 font-semibold tabular-nums text-neutral-700">
          {qe.questionKey.toUpperCase()}
        </span>
        {unavailable ? (
          <Badge tone="neutral">Transcript unavailable</Badge>
        ) : (
          <Badge tone={RELEVANCE_TONE[qe.relevance]}>{RELEVANCE_LABEL[qe.relevance]}</Badge>
        )}
        {!unavailable
          ? qe.rubric.map((r) => (
              <Badge key={r.rubricKey} tone={COVERAGE_TONE[r.coverage]} pill>
                {rubricLabels.get(r.rubricKey) ?? r.rubricKey}: {COVERAGE_LABEL[r.coverage]}
              </Badge>
            ))
          : null}
        <span className="ml-auto text-neutral-400" aria-hidden>
          {expanded ? "▾" : "▸"}
        </span>
      </button>

      {expanded ? (
        <div className="space-y-2 border-t border-neutral-200 p-2">
          {answer ? <p className="text-neutral-800">{answer.prompt}</p> : null}

          <div>
            <p className="text-[11px] font-medium uppercase tracking-wide text-neutral-500">
              {mode === "typed"
                ? "Typed answer"
                : mode === "voice"
                  ? "Spoken answer (transcript)"
                  : "Answer"}
              {mode === "voice" && startMs !== null ? (
                <span className="ml-2 normal-case tracking-normal text-neutral-400">
                  starts at {fmtOffset(startMs)} in the recording
                </span>
              ) : null}
            </p>
            {unavailable ? (
              <p className="mt-1 text-neutral-500">Transcript unavailable for this answer.</p>
            ) : mode === null ? (
              <p className="mt-1 text-neutral-500">Not answered.</p>
            ) : answer?.text ? (
              <p className="mt-1 whitespace-pre-wrap rounded-md bg-neutral-50 p-2 text-neutral-700">
                {answer.text}
              </p>
            ) : (
              <p className="mt-1 text-neutral-500">No words were recorded for this answer.</p>
            )}
          </div>

          {!unavailable && qe.relevanceNote ? (
            <p className="text-neutral-600">{qe.relevanceNote}</p>
          ) : null}

          {!unavailable && qe.rubric.length > 0 ? (
            <ul className="space-y-2">
              {qe.rubric.map((r) => (
                <li key={r.rubricKey}>
                  <div className="flex flex-wrap items-center gap-2">
                    <span className="font-medium text-neutral-700">
                      {rubricLabels.get(r.rubricKey) ?? r.rubricKey}
                    </span>
                    <Badge tone={COVERAGE_TONE[r.coverage]}>{COVERAGE_LABEL[r.coverage]}</Badge>
                  </div>
                  {r.note ? <p className="mt-1 text-neutral-600">{r.note}</p> : null}
                  {r.quotes.map((quote, i) => (
                    <Quote key={i}>{quote}</Quote>
                  ))}
                </li>
              ))}
            </ul>
          ) : null}
        </div>
      ) : null}
    </li>
  );
}

function Quote({ children }: { children: ReactNode }) {
  return (
    <blockquote className="mt-1 border-l-2 border-brand-200 pl-2 italic text-neutral-700">
      {children}
    </blockquote>
  );
}
